// Automatically generated by astro-icon
// 8dbb85d3aa0ed967cb5611946aea7cebd797c0d41aba6d0c5b2f8f1a35433adc

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "aftereffects"
		| "androidstudio"
		| "animate"
		| "apple"
		| "arc"
		| "archlinux"
		| "chatgpt"
		| "chrome"
		| "firefox"
		| "illustrator"
		| "neovim"
		| "notion"
		| "photoshop"
		| "premiere"
		| "qt"
		| "safari"
		| "sublime"
		| "tailscale"
		| "typora"
		| "ubuntu"
		| "unity"
		| "vscode"
		| "warp"
		| "windows11"
		| "zerotier";
}